import {
  RiMusic2Line,
  RiWifiLine,
  RiWindyLine,
  RiParkingLine,
  RiDropLine,
  RiCupLine,
  RiGobletLine,
  RiRestaurantLine,
  RiLeafLine,
  RiPlantLine,
  RiSunLine,
  RiDoorLine,
  RiVolumeUpLine,
  RiMicLine,
  RiSlideshowLine,
  RiBuildingLine,
  RiHeartPulseLine,
  RiFlashlightLine,
  RiShieldCheckLine,
  RiVipCrownLine,
  RiEBike2Line,
  RiShoppingBag3Line,
} from "react-icons/ri";
import type { ElementType } from "react";

// Canonical amenity names (see amenityOptions.ts) → icons.
export const amenityIcons: Record<string, ElementType> = {
  "Live Music":      RiMusic2Line,
  "WiFi":            RiWifiLine,
  "AC":              RiWindyLine,
  "Parking":         RiParkingLine,
  "Pool":            RiDropLine,
  "Cafe":            RiCupLine,
  "Bar":             RiGobletLine,
  "Restaurant":      RiRestaurantLine,
  "Gym":             RiHeartPulseLine,
  "Spa":             RiLeafLine,
  "Garden":          RiPlantLine,
  "Rooftop":         RiBuildingLine,
  "Outdoor Seating": RiSunLine,
  "Private Rooms":   RiDoorLine,
  "Catering":        RiRestaurantLine,
  "Sound System":    RiVolumeUpLine,
  "Projector":       RiSlideshowLine,
  "Stage":           RiMicLine,
  "Generator":       RiFlashlightLine,
  "Security":        RiShieldCheckLine,
  "VIP Tables":      RiVipCrownLine,
  "Dance Floor":     RiMusic2Line,
  "Delivery":        RiEBike2Line,
  "Takeaway":        RiShoppingBag3Line,
  "Breakfast":       RiCupLine,
};
